### PR TITLE
Overview, search, touchups, refactor

### LINKED ISSUE #4: Add basic search functionality
I think it would be useful for people to be able to quickly check (without having to download the whole dataset) if there is a particular class/phylum/country/region, and how many samples it has. Just a basic search box that returns a list of results, like:

`Search: Sah`

|Match|Type|Samples|
|-|-|-|
|Sub-saharan Africa|Region|12,345|
|saharious firmicutes|Class|678|

etc.

### LINKED ISSUE #6: Show first N rows of data set just to show what data looks like?
Show first several number of rows just to show what fields/cols/etc are in the data. Sort of a "screenshot preview".

### LINKED ISSUE #9: Dataset high level metadata
It's usually nice, for advertising purposes, to "show off" how many X we have in the data. Here are some thing we might want to show off right at the top of the website, either in paragraph "hero" form, or in [tile form](https://github.com/blekhmanlab/compendium_website/assets/8326331/0a500631-e3fc-4ea3-a71f-f1c1934f3fb8):

- number of samples
- number of projects?
- number of classes/phyla?
- countries/regions?
- size of the dataset download?

### PR DESCRIPTION
**Pull request by vincerubinetti**
Closes #4 
Closes #9 
Closes #6 

- add css prop sort prettier plugin
- do some naming clarifications (e.g. phyla vs phylum)
- add compile pre process step for projects
- derive metadata from the existing data i already have
- add overview section with tiles of metadata
- add accordion component for recipes
- make button component into anchor or button tag
- add textbox component for search
- get data types directly from json
- refactor map code a bit
- style changes
- add search section with collated data, fuzzy (trigram) search, and results in table format. try searching "mali" for exact and fuzzy matches.

### CODE REVIEW

**Review by rabdill — APPROVED** [review]
Looks good to me. I added one very minor change; if that's ok with you, good to merge!

**Comment by vincerubinetti** [comment]
are there more specific names for anything else in that list? Like a sample name, or scientific class?

We could also put the more specific details in a tooltip on question mark Icon. might want to do this anyway somewhere on the page to explain where each piece of data comes from.

**Comment by rabdill** [comment]
> are there more specific names for anything else in that list too? Like a sample name, or scientific class?
>
> We could also put the more specific details in a tooltip on question mark Icon. might want to do this anyway somewhere on the page to explain where each piece of data (eg iso country name) comes from.

Tooltips could be cool! The "sample" entries in the table are more specifically "SRA run accession numbers," which I'll add now. The regional groupings are pulled from the [U.N. Sustainable Development Goals](https://unstats.un.org/sdgs/indicators/regional-groups/) project, but that would probably be less clunky as a tooltip.

**Comment by vincerubinetti** [comment]
Your latest commit looks good to me. It just looked a little awkward before where only one item in the list was very specific.

Regarding the UN regions, natural earth, etc., we can at some point add a short paragraph at the bottom, giving a high level acknowledgement of sources and such.

**Comment by vincerubinetti** [comment]
Reworded things to simplify a bit and distinguish between what the user does, what the meaning of each term is, and what they get (e.g. technically they don't "Search for sample counts grouped by...", they search for the name of one of the things and get back the name, type, count). Also added a way to put tooltips on words. Let me know if this is okay and modify as necessary.

**Comment by rabdill** [comment]
I'm having trouble coming up with text that is totally consistent between the tips ("Collection of multiple samples" vs "Taxon observed in sample" seems weird), but it's at least close, and it looks so better with the tooltips. Thanks.

**Pull request merged**
